### ISSUE TITLE
SyntaxError: Invalid or unexpected token, trying to run/start NPM npm 

### ISSUE THREAD

**Issue by qonteo** [VladimirMikulic/sms-gaming#4]
Hello Vladimir,
I've found your references on Twilio's websites, when I was looking for WhatsApp's apps. 
As indicated the README.MD, I've cloned the repository, installed your app with npm -i and tried to start NPM, however, it threw the following  error.

I went to the respective file /var/www/qonteo/sms-gaming/lib/games/GameFactory.js, but before forking anything I decided to ask you first! rsrsrs.

How should I fix your app i order to run in in my server?

Best wishes,
I

/sms-gaming$ npm start

> sms-gaming@1.0.0 start /var/www/qonteo/sms-gaming
> nodemon lib/app.js

[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node lib/app.js`
/var/www/qonteo/sms-gaming/lib/games/GameFactory.js:4
  static #games = [
         ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/qonteo/sms-gaming/lib/messages.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by VladimirMikulic** [comment]
Hi! Make sure that you are running Node version 12 or greater and it will work just fine!

**Comment by qonteo** [comment]
Great! I've upgraded NodeJs to v12 then it works now. 
My Twilio account has no such key (session_key).  There are only TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN 

What session_secret must I use? 

/sms-gaming$ npm start

> sms-gaming@1.0.0 start /var/www/qonteo/sms-gaming
> nodemon lib/app.js

[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node lib/app.js`
express-session deprecated req.secret; provide secret option lib/app.js:24:9
Server started on port 3000
Error: secret option required for sessions
    at session (/var/www/qonteo/sms-gaming/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:317:13)
    at /var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/www/qonteo/sms-gaming/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:317:13)
    at /var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:284:7
^X^C

**Comment by VladimirMikulic** [comment]
Hi @qonteo. `SESSION_SECRET` is a string (generate at will) used to secure your session.
