### ISSUE TITLE
Error: secret option required for sessions

### ISSUE THREAD

**Issue by qonteo** [VladimirMikulic/sms-gaming#5]
Vladimir,
We could improve your source by adding  this chunk 

var app = express();
app.use(require('express-session')({ secret: 'keyboard cat', resave: true, saveUninitialized: true }));

That way, no one need to bother about session_secret anymore

$ npm start

> sms-gaming@1.0.0 start /var/www/qonteo/sms-gaming
> nodemon lib/app.js

[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node lib/app.js`
express-session deprecated req.secret; provide secret option lib/app.js:24:9

Server started on port 3000
Error: secret option required for sessions
    at session (/var/www/qonteo/sms-gaming/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:317:13)
    at /var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/var/www/qonteo/sms-gaming/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:317:13)
    at /var/www/qonteo/sms-gaming/node_modules/express/lib/router/index.js:284:7
^X^C

**Comment by VladimirMikulic** [comment]
Check out #4 for my input.
